"""add page metadata table

Revision ID: 57814870cf26
Revises: 457a1fc32e56
Create Date: 2026-08-23 17:30:51.864968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57814870cf26'
down_revision = '457a1fc32e56'
branch_labels = None
depends_on = None


def upgrade():
    inspector = sa.inspect(op.get_bind())
    tables = set(inspector.get_table_names())

    if 'page_meta' not in tables:
        op.create_table('page_meta',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('endpoint', sa.String(length=250), nullable=False),
        sa.Column('title', sa.String(length=250), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=False),
        sa.Column('image_url', sa.String(length=500), nullable=True),
        sa.Column('og_type', sa.String(length=50), nullable=False),
        sa.Column('is_indexable', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('endpoint')
        )

    drop_column_if_exists('posts', 'date', inspector)
    drop_column_if_exists('projects', 'date', inspector)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    op.drop_table('page_meta')
    # ### end Alembic commands ###


def drop_column_if_exists(table_name, column_name, inspector):
    if table_name not in inspector.get_table_names():
        return

    columns = {column['name'] for column in inspector.get_columns(table_name)}

    if column_name in columns:
        with op.batch_alter_table(table_name, schema=None) as batch_op:
            batch_op.drop_column(column_name)
